name: gh-pages Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies and Build
        run: npm install --if-present && npm run build --if-present
      - name: Configure git
        run: git config user.name "{{ github.actor }}" && git config user.email "{{ github.actor }}@users.noreply.github.com" && git fetch origin
      - name: Clean up an Copy
        run: npm run build && mkdir dist/photographer && cp -r dist/index.html dist/photographer && git add . && git commit -m 'deploy'
      - name: Push to gh-pages
        run: git push origin --delete gh-pages && git subtree push --prefix dist origin gh-pages